name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: gcloud Auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          token_format: access_token

      - name: Login to gcr
        run: |
          echo "${{ steps.auth.outputs.access_token }}" | docker login -u oauth2accesstoken --password-stdin https://gcr.io

      - name: Build Push and Deploy
        run: |
          docker build -t home .
          
          docker tag home gcr.io/dbut-0/home:latest
          docker tag home gcr.io/dbut-0/home:${{ github.sha }}
          
          docker push gcr.io/dbut-0/home:latest
          docker push gcr.io/dbut-0/home:${{ github.sha }}

      - id: Deploy
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: home
          region: australia-southeast2
          image: gcr.io/dbut-0/home:${{ github.sha }}
