name: Quality
on:
  pull_request:
    branches:
    - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-contrib/golangci-lint@v1
      env:
        GO111MODULE: "on"
        GOFLAGS: "-mod=vendor"

  coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run coverage tool
      uses: ./.github/actions/coverage-action
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      with:
        soft_target: 90
        hard_target: 87
        token: ${{ secrets.ORG_GITHUB_TOKEN }}
        ignore: "github.com/anzx/fabric-entitlements/test/util,github.com/anzx/fabric-entitlements/avrobuf/proto"
